name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Lint & Test'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Enable corepack
        run: corepack enable

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Validate Renovate config
        run: pnpm test
